D=dict([('quiz1',34.5),('quiz2',34),('quiz3',30),('quiz4',27),('quiz5',20)])
maximum=max(D.values())
minimum=min(D.values())
print("Maximum quiz score is",maximum)
print("Minimum quiz score is", minimum)